version: '2.1'

services:
  api:
    image: vibioh/mjml
    labels:
      traefik.http.routers.mjml-http.rule: Host(`mjml.vibioh.fr`)
      traefik.http.routers.mjml-http.entrypoints: http
      traefik.http.routers.mjml-http.middlewares: redirect@file
      traefik.http.routers.mjml-https.rule: Host(`mjml.vibioh.fr`)
      traefik.http.routers.mjml-https.entrypoints: https
      traefik.http.routers.mjml-https.middlewares: compress@file, web-limit@file, mjml-auth
      traefik.http.routers.mjml-https.tls: true
      traefik.http.routers.mjml-https.tls.certresolver: default
      traefik.http.services.mjml-service.loadbalancer.server.port: '1080'
      traefik.http.middlewares.mjml-auth.basicauth.removeheader: true
      traefik.http.middlewares.mjml-auth.basicauth.users: '${HTTP_PASSWORD}'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 134217728
    security_opt:
    - no-new-privileges
